### ISSUE TITLE
detach(s::Signal) does not make s unreachable from the children of s

### ISSUE THREAD

**Issue by Jasha10** [TsurHerman/Signals.jl#9]
Hi @TsurHerman, thanks for your awesome work on this package.

There is one issue I found (and please correct me if I am mistaken):
`detach(s)` does not remove `s` completely from this signal graph, because some children of `s` might have a dependency on `s` via their pull action. In particular, `s` might still be reachable through the pull action of another signal, which would prevent `s` from being garbage-collected. For example:
```
A = Signal(123)
B = Signal(A) do a
    a + 1
end
@assert B() == 124
detach(A)
@assert A === B.action.args[1]
```
This goes to show that, so long as `B` is reachable, `A` cannot be garbage-collected because `B`'s args include `A`.

**Comment by Jasha10** [comment]
As far as how to address this issue: Perhaps a loop could be added to the `detach(A)` function that checks each element `B` of `A.children` to see if `A` is listed as an element of `B.action.args`? But this brings up the question: how should the dependent child `B` be modified?

One idea is that if `B.action.args` contains `A` as one of its elements, that element of `B.action.args` could be replaced with the constant value `A[]` that `A` had at the time when `detach(A)` was called. Of course, `A` could occur several times in the vector `B.action.args`. Not sure if this is the best way to go about it...

**Comment by Jasha10** [comment]
On a related note, I feel that it might be a good idea for `detach(A)` to call `empty!(A.children)` as well, so that the child `B` will no longer be affected if a new value is pushed to `A` after `detach(A)` has been called.

Alternatively, the `detach` functionality could be broken up into several functions such as `detach_children`, `detach_binders`, and `detach_parents`, with `detach(s::Signal)` calling all three of the aforementioned to completely remove `s` from the signal graph.

**Comment by TsurHerman** [comment]
Thank you @Jasha10.

you are correct, `detach` does not remove a signal from its `children` `action.args`, it still holds a reference to the necessary value. 

Only when its children will be detached or unreferenced it will truly be ready for gc.


> One idea is that if `B.action.args` contains `A` as one of its elements, that element of `B.action.args` could be replaced with the constant value `A[]` that `A` had at the time when `detach(A)` was called. Of course, `A` could occur several times in the vector `B.action.args`. 

The problem is that action.args are immutable (struct). you could "replace" a signal with another signal theoretically but that would require replacing every signal all the way to the terminal nodes.

another reason not do it, is as mentioned in a previous [issue](https://github.com/TsurHerman/Signals.jl/issues/8#issue-457850913) is that you might want to
temporarly `detach` a signal(make it stop reciving updates) , and then maybe later `reatach` it (not yet implemented)

**Comment by Jasha10** [comment]
I see. Thank you for the explanation.
